[project]
name = "ai"
version = "0.1.0"
description = "Add a short description here"
authors = ["Veronika Gillies <veronikamwinters@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
langchain = "0.0.323.*"
openai = "0.28.1.*"
beautifulsoup4 = "4.12.2.*"
networkx = "3.2.*"
tiktoken = "0.5.1.*"
